
const KEY='gokuldham_crm_v1';
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{properties:[],leads:[],settings:{phone:'9518035504',rateMin:40000,rateMax:45000}};
function saveDB(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function show(id,btn){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(id==='reports')renderReports()}
function score(l){let s=25;if(l.budget>0)s+=25;if(l.size>0)s+=15;if(l.pref)s+=15;if(['Interested','Site Visit','Negotiation'].includes(l.status))s+=20;return Math.min(100,s)}
function renderAll(){renderDashboard();renderProperties();renderLeads();renderReports()}
function renderDashboard(){
const p=db.properties.filter(x=>x.status==='Available').length, hot=db.leads.filter(x=>score(x)>=75).length, sv=db.leads.filter(x=>x.status==='Site Visit').length, closed=db.leads.filter(x=>x.status==='Closed').length;
document.getElementById('metrics').innerHTML=[['Resale Available',p],['New Leads',db.leads.filter(x=>x.status==='New').length],['Hot Leads',hot],['Site Visits',sv],['Closed',closed],['Rate Range','₹40–45K']].map(x=>`<div class="card"><div class="metric">${x[1]}</div><div class="label">${x[0]}</div></div>`).join('');
const today=new Date().toISOString().slice(0,10);let arr=db.leads.filter(x=>x.follow===today||score(x)>=75).slice(0,6);
document.getElementById('priorities').innerHTML=arr.length?arr.map(l=>`<div class="item"><b>${esc(l.name)}</b> <span class="badge ${score(l)>=75?'hot':'warm'}">${score(l)}/100</span><div class="small">${esc(l.mobile||'')} · ${esc(l.status)} · Follow-up ${l.follow||'—'}</div></div>`).join(''):'<div class="muted">No priority leads today.</div>';
}
function renderProperties(){
let q=(document.getElementById('pSearch')?.value||'').toLowerCase(), st=document.getElementById('pStatus')?.value||'';
let a=db.properties.filter(p=>(!st||p.status===st)&&(`${p.plotNo} ${p.size} ${p.loc}`.toLowerCase().includes(q)));
document.getElementById('propertyList').innerHTML=a.length?a.map(p=>`<div class="item"><div class="row between"><b>Plot ${esc(p.plotNo)}</b><span class="badge ${p.status==='Available'?'available':''}">${p.status}</span></div><div class="small">${p.size} Sq.Yd. · ${p.asking?money(p.asking):'Price not entered'} · ${[p.corner==='Yes'?'Corner':'',p.park==='Yes'?'Park facing':'',p.road50==='Yes'?'50-ft road':''].filter(Boolean).join(' · ')||'Standard'}</div><div class="row" style="margin-top:8px"><button onclick="editProperty('${p.id}')">Edit</button><button class="danger" onclick="delProperty('${p.id}')">Delete</button></div></div>`).join(''):'<div class="muted">No properties entered yet. Add only verified resale inventory.</div>';
}
function openProperty(p={}){pid.value=p.id||'';plotNo.value=p.plotNo||'';plotSize.value=p.size||'';asking.value=p.asking||'';propStatus.value=p.status||'Available';corner.value=p.corner||'No';park.value=p.park||'No';road50.value=p.road50||'No';ploc.value=p.loc||'';propertyDlg.showModal()}
function editProperty(id){openProperty(db.properties.find(x=>x.id===id)||{})}
function saveProperty(e){e.preventDefault();let o={id:pid.value||uid(),plotNo:plotNo.value.trim(),size:Number(plotSize.value),asking:Number(asking.value||0),status:propStatus.value,corner:corner.value,park:park.value,road50:road50.value,loc:ploc.value.trim()};let i=db.properties.findIndex(x=>x.id===o.id);i>=0?db.properties[i]=o:db.properties.push(o);propertyDlg.close();saveDB()}
function delProperty(id){if(confirm('Delete this property record?')){db.properties=db.properties.filter(x=>x.id!==id);saveDB()}}
function renderLeads(){let q=(document.getElementById('lSearch')?.value||'').toLowerCase(),st=document.getElementById('lStatus')?.value||'';let a=db.leads.filter(l=>(!st||l.status===st)&&(`${l.name} ${l.mobile} ${l.pref} ${l.note}`.toLowerCase().includes(q)));document.getElementById('leadList').innerHTML=a.length?a.map(l=>`<div class="item"><div class="row between"><b>${esc(l.name)}</b><span class="badge ${score(l)>=75?'hot':score(l)>=50?'warm':''}">${score(l)}/100</span></div><div class="small">${esc(l.mobile||'')} · ${esc(l.status)} · ${esc(l.source)} · Budget ${l.budget?money(l.budget):'—'}</div><div class="small">Need: ${l.size||'—'} Sq.Yd. · ${esc(l.pref||'Any')} · Follow-up ${l.follow||'—'}</div><div class="row" style="margin-top:8px"><button onclick="editLead('${l.id}')">Edit</button>${l.mobile?`<a class="btn" href="tel:${encodeURIComponent(l.mobile)}">Call</a><a class="btn secondary" href="https://wa.me/91${l.mobile.replace(/\\D/g,'')}" target="_blank">WhatsApp</a>`:''}<button class="danger" onclick="delLead('${l.id}')">Delete</button></div></div>`).join(''):'<div class="muted">No leads yet.</div>'}
function openLead(l={}){lid.value=l.id||'';lname.value=l.name||'';lmobile.value=l.mobile||'';lbudget.value=l.budget||'';lsize.value=l.size||'';lsource.value=l.source||'Facebook';lstatus.value=l.status||'New';lpref.value=l.pref||'';lfollow.value=l.follow||'';lnote.value=l.note||'';leadDlg.showModal()}
function editLead(id){openLead(db.leads.find(x=>x.id===id)||{})}
function saveLead(e){e.preventDefault();let o={id:lid.value||uid(),name:lname.value.trim(),mobile:lmobile.value.trim(),budget:Number(lbudget.value||0),size:Number(lsize.value||0),source:lsource.value,status:lstatus.value,pref:lpref.value.trim(),follow:lfollow.value,note:lnote.value.trim(),updated:new Date().toISOString()};let i=db.leads.findIndex(x=>x.id===o.id);i>=0?db.leads[i]=o:db.leads.push(o);leadDlg.close();saveDB()}
function delLead(id){if(confirm('Delete this lead?')){db.leads=db.leads.filter(x=>x.id!==id);saveDB()}}
function money(n){return '₹'+Number(n).toLocaleString('en-IN')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function generatePost(){
let topic=mTopic.value, p=mPlot.value.trim(), available=db.properties.filter(x=>x.status==='Available'),best=available[0];let focus=p?`Plot/feature: ${p}`:(best?`Resale option: Plot ${best.plotNo}, ${best.size} Sq.Yd.`:'Verified resale inventory is limited; ask for current options.');
let text=`Gokul Dham Sector-13, Hansi — Resale Property Opportunity\\n\\n${topic}\\n\\n${focus}\\n\\nCurrent general resale range: ₹40,000–₹45,000 per Sq.Yd. Premium location features such as corner, park-facing and 50-feet road can command a different rate.\\n\\n✔ Planned sector layout\\n✔ Parks and road connectivity\\n✔ Resale opportunities subject to verified availability\\n\\n📞 Call / WhatsApp: 9518035504\\n\\nSite visit ke liye sampark karein.\\n\\n#GokulDham #Hansi #Property #ResalePlot #HansiProperty`;
postOutput.style.display='block';postOutput.innerHTML=`<h3>Post Draft</h3><textarea id="postText">${esc(text)}</textarea><div class="row" style="margin-top:8px"><button onclick="navigator.clipboard.writeText(postText.value)">Copy</button><a class="btn secondary" target="_blank" href="https://www.facebook.com/">Open Facebook</a></div>`}
function renderReports(){let total=db.leads.length,src={};db.leads.forEach(l=>src[l.source]=(src[l.source]||0)+1);let sizes={};db.leads.forEach(l=>{if(l.size)sizes[l.size]=(sizes[l.size]||0)+1});let top=Object.entries(sizes).sort((a,b)=>b[1]-a[1])[0];document.getElementById('reportContent').innerHTML=`<div class="grid cards"><div class="card"><div class="metric">${total}</div><div class="label">Total leads</div></div><div class="card"><div class="metric">${db.properties.filter(p=>p.status==='Available').length}</div><div class="label">Available resale</div></div><div class="card"><div class="metric">${db.leads.filter(l=>score(l)>=75).length}</div><div class="label">Hot leads</div></div></div><div class="card" style="margin-top:12px"><h3>Demand signals</h3><p><b>Top requested size:</b> ${top?esc(top[0])+' Sq.Yd.':'Not enough data yet'}</p><p><b>Lead sources:</b> ${Object.entries(src).map(x=>esc(x[0])+': '+x[1]).join(' · ')||'No leads yet'}</p><p><b>Approved general rate:</b> ₹40,000–₹45,000/Sq.Yd.</p><p class="small muted">Premium features may have different asking rates. Do not publish an unverified plot or price.</p></div><div class="card" style="margin-top:12px"><h3>Backup</h3><button onclick="backup()">Download Backup JSON</button> <label class="btn secondary">Restore JSON<input type="file" accept=".json" hidden onchange="restore(event)"></label></div>`}
function backup(){let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gokul-dham-crm-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function restore(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.properties)||!Array.isArray(x.leads))throw Error();db=x;saveDB();alert('Backup restored.')}catch{alert('Invalid backup file.')}};r.readAsText(f)}
renderAll();
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});
